In [4]:
#birden fazla karar ağacının birleştirilmesi..
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split,ShuffleSplit,GridSearchCV
from sklearn.metrics import mean_squared_error,r2_score
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.tree import DecisionTreeRegressor,DecisionTreeClassifier
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import BaggingRegressor

In [20]:
hit = pd.read_csv('Hitters.csv')
df=hit.copy()
df=df.dropna()
ms=pd.get_dummies(df[['League','Division','NewLeague']])
y=df['Salary']
X_=df.drop(['Salary','League','Division','NewLeague'],axis=1).astype('float64')
X=pd.concat([X_,ms[['League_N','Division_W','NewLeague_N']]],axis=1)

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)


In [23]:
bag_model=BaggingRegressor(bootstrap_features=True)
bag_model.fit(X_train,y_train)

BaggingRegressor(base_estimator=None, bootstrap=True, bootstrap_features=True,
                 max_features=1.0, max_samples=1.0, n_estimators=10,
                 n_jobs=None, oob_score=False, random_state=None, verbose=0,
                 warm_start=False)

In [26]:
predicted=bag_model.predict(X_test)
np.sqrt(mean_squared_error(predicted,y_test))

323.63004112668386

In [10]:
bag_model.estimators_ #her bir ağaca bakalım

[DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                       max_leaf_nodes=None, min_impurity_decrease=0.0,
                       min_impurity_split=None, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       presort=False, random_state=452947648, splitter='best'),
 DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                       max_leaf_nodes=None, min_impurity_decrease=0.0,
                       min_impurity_split=None, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       presort=False, random_state=2090565771, splitter='best'),
 DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                       max_leaf_nodes=None, min_impurity_decrease=0.0,
                       min_impurity_split=None, min_samples_leaf=1,
                       min_samples_split=2, min_w

In [11]:
bag_model.estimators_samples_ # her bir ağacın örnekleri

[array([100,  12,  97,  33,  34,  94,  70, 166, 154, 147,  88,   6, 143,
        106, 134,  38,   1, 134,  66, 186,  94, 164, 103, 162,  37,  34,
        106,  46,   5,   9,  51, 149, 125, 111, 132, 162,  99,  36,  41,
        104, 150,  28,  80, 120, 139,  90, 105,  95,  85, 177, 154, 100,
        105,  60,  24,  65,  49,  43,  60,  27,   9, 193,  94,  38,   1,
         99,  83, 137,  92,  52, 118,  31,  21,  59,  60, 140,  33,  10,
        195,  11,  96,  51,  38, 139, 158,  54,  81,  11,  63, 181, 157,
        174, 151, 162,  98, 162,  35, 193,  76,  12,  97, 135, 181,  43,
         20, 104, 147, 111,  29, 174, 131, 157,  68, 194,  48, 101,   8,
         76,  98, 106,  52,  26,  83, 182,  60, 132, 102,  99, 137,  33,
        101,  43,  54, 168,   1,  25, 104, 106,  46,  61,  36, 100, 149,
         19, 176, 132,  55,  59, 184,  59,  29,  93,  29,  62,  13,  31,
        116, 148,   2,  43, 164,  16, 103, 194,  77, 152,  72, 112,  36,
         89,  14,  47,  36,   6,  22, 106,  65,  24

In [13]:
bag_model.estimators_features_ #her bir ağacın kullandığı değişkenler

[array([14,  5,  6, 14,  5, 18,  3, 17,  9,  8,  8,  1,  9, 17,  6,  3,  1,
        10,  4]),
 array([ 2, 10,  6,  5,  7, 16,  6,  8,  5, 15, 11,  5,  8, 17,  6, 17, 10,
         0, 12]),
 array([ 8, 17, 12,  8, 11,  2, 15,  2, 18, 15,  5, 13,  1,  9,  2, 12, 18,
         2, 12]),
 array([ 7, 17,  4, 12, 18,  0,  1, 16, 15,  6,  4,  5,  9,  9,  3, 10,  2,
        11,  4]),
 array([14, 13, 13, 15, 12,  6,  6,  3,  3,  5,  9,  7,  2,  3,  8,  9, 15,
         2,  8]),
 array([ 1, 10,  5, 18,  0,  8,  9, 12,  1, 17,  6,  5,  6, 16, 12, 12, 11,
        11, 18]),
 array([13, 18, 13,  2, 10, 18, 17, 16,  7,  1, 12, 18,  7, 12,  7, 11, 11,
         4, 17]),
 array([18, 15, 17,  2, 10, 13, 15, 13, 12,  5,  5,  0, 13,  5,  1, 10, 15,
         3, 11]),
 array([ 6, 17, 11,  0,  4,  4,  0, 14, 16,  3,  4, 14, 13,  1, 18,  7, 17,
         5, 17]),
 array([ 5, 11, 13, 17,  0, 10,  9,  0,  7,  8, 14,  1,  2, 10,  8,  5,  5,
         3, 13])]

In [15]:
bag_model.estimators_[1]#ağaçların özellikleri

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=2090565771, splitter='best')

In [16]:
#sadece ikinci ağacın tahminini görme

In [27]:
iki_y_pred=bag_model.estimators_[1].fit(X_train,y_train).predict(X_test)

In [29]:
np.sqrt(mean_squared_error(iki_y_pred,y_test))

458.5457933144836

In [31]:
#bu ağaç malın önde gideniymiş, bunu kırbaçlayacağız ilerde.

In [32]:
#HERE TUNING REIS COMES.....

In [33]:
bag_model=BaggingRegressor(bootstrap_features=True)
bag_model.fit(X_train,y_train)

BaggingRegressor(base_estimator=None, bootstrap=True, bootstrap_features=True,
                 max_features=1.0, max_samples=1.0, n_estimators=10,
                 n_jobs=None, oob_score=False, random_state=None, verbose=0,
                 warm_start=False)

In [35]:
bag_params = {'n_estimators': range(2,20)}

In [44]:
bag_dummy_model=BaggingRegressor(random_state=42)
bag_dummy_model.fit(X_train,y_train)

BaggingRegressor(base_estimator=None, bootstrap=True, bootstrap_features=False,
                 max_features=1.0, max_samples=1.0, n_estimators=10,
                 n_jobs=None, oob_score=False, random_state=42, verbose=0,
                 warm_start=False)

In [50]:
bag_cv_model=GridSearchCV(bag_dummy_model,bag_params,cv=10)

In [51]:
bag_cv_model.fit(X_train,y_train)

C:\Users\Samet Sökel\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv=10, error_score='raise-deprecating',
             estimator=BaggingRegressor(base_estimator=None, bootstrap=True,
                                        bootstrap_features=False,
                                        max_features=1.0, max_samples=1.0,
                                        n_estimators=10, n_jobs=None,
                                        oob_score=False, random_state=42,
                                        verbose=0, warm_start=False),
             iid='warn', n_jobs=None, param_grid={'n_estimators': range(2, 20)},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [52]:
bag_cv_model.best_params_

{'n_estimators': 14}

In [53]:
bag_tuned=BaggingRegressor(random_state=42,n_estimators=14)
bag_tuned.fit(X_train,y_train)

BaggingRegressor(base_estimator=None, bootstrap=True, bootstrap_features=False,
                 max_features=1.0, max_samples=1.0, n_estimators=14,
                 n_jobs=None, oob_score=False, random_state=42, verbose=0,
                 warm_start=False)

In [54]:
predictedtuned=bag_tuned.predict(X_test)
np.sqrt(mean_squared_error(predictedtuned,y_test))

363.89112389223493