In [68]:
import pandas as pd
import statsmodels.api as sm
from sklearn.model_selection import train_test_split,cross_val_score,cross_val_predict
ad=pd.read_csv("Advertising.csv")
df=ad.copy()

In [56]:
X=df.drop("sales",axis=1)
X=X.drop("Unnamed: 0",axis=1)

In [57]:
y=df["sales"]

In [65]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20, random_state=71)

In [74]:
training=df.copy()

In [64]:
## Statsmodels ile çoklu lineer regresyon

In [88]:
lm=sm.OLS(y_train,X_train)
model=lm.fit()



In [79]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                  sales   R-squared (uncentered):                   0.985
Model:                            OLS   Adj. R-squared (uncentered):              0.985
Method:                 Least Squares   F-statistic:                              3497.
Date:                Fri, 22 May 2020   Prob (F-statistic):                   1.74e-143
Time:                        23:23:26   Log-Likelihood:                         -325.17
No. Observations:                 160   AIC:                                      656.3
Df Residuals:                     157   BIC:                                      665.6
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
TV             0.0535      0.001     39.193      0.000       0.051       0.056
radio          0.2321      0.010     23.287      0.000       0.212       0.252
newspaper      0.0109      0.007      1.614      0.109      -0.002       0.024
==============================================================================
Omnibus:                        3.721   Durbin-Watson:                   1.892
Prob(Omnibus):                  0.156   Jarque-Bera (JB):                3.503
Skew:                           0.362   Prob(JB):                        0.174
Kurtosis:                       3.032   Cond. No.                         13.1
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [86]:
model.predict([224,2.4,15.6])

array([12.71895705])

In [89]:
###Aynı modeli scikit-learn ile kurmaya çalışacağım

In [118]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score
import numpy as np

In [91]:
reg=LinearRegression()

In [92]:
skmodel=reg.fit(X_train,y_train)

In [141]:
skmodel.intercept_ #Sabit sayı

3.051251890550546

In [142]:
skmodel.coef_ #değişken katsayıları

array([ 0.04512516,  0.19639366, -0.00551856])

In [154]:
print("sales = 0.04TV + 0.19radio -0.005newspaper + 3.05")

sales = 0.04TV + 0.19radio -0.005newspaper + 3.05


In [166]:
skmodel.predict(yeni_veri)

array([6.14820102])

In [159]:
yeni_veri=pd.DataFrame([[30],[10],[40]]).T
yeni_veri

0   1   2
0  30  10  40

In [167]:
rmse=np.sqrt(mean_squared_error(y_train,skmodel.predict(X_train)))
rmse#Eğitim hatası

1.4597231352972841

In [170]:
rmse=np.sqrt(mean_squared_error(y_test,skmodel.predict(X_test)))
rmse#Test hatası

2.3468584425523313

In [171]:
#Test hatası niye uçtu amk overfit mi ettik